project_id = "dcwqdesukkexizcjiwpd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.process-spreadsheet]
verify_jwt = false

[functions.extract-quotes]
verify_jwt = false

[functions.queue-job]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.job-status]
verify_jwt = false