// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcwqdesukkexizcjiwpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjd3FkZXN1a2tleGl6Y2ppd3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTY0NjYsImV4cCI6MjA2NjQ3MjQ2Nn0.eY59ZozAz-uAjug7so1MqqORlu8517mVyX_O8fF_YSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);